SELECT -- FIRST 10 SKIP 20
    A2.WEEK2 AS WEEK2,
    A2.DATE2 AS DATE2,
    A2.GRUPO_CAMARA AS GRUPO_CAMARA,
    A2.EVENT_TYPE2 AS EVENT_TYPE2,
    A2.CAMERA AS CAMERA,
    COUNT(A2.CAMERA) AS TOTAL_COUNT
FROM
    (
        SELECT
            A.*,
            ( EXTRACT(WEEK FROM A.START_DATE) ) AS WEEK2,
            ( EXTRACT(DAY FROM A.START_DATE) || '/' || EXTRACT(MONTH FROM A.START_DATE) || '/' || EXTRACT( YEAR FROM A.START_DATE) ) AS DATE2,
            CASE
                WHEN 1 <= A.CAMERA AND A.CAMERA <= 4 THEN 'PARQUEOS PUBLICOS PUERTA # 1'
                WHEN 5 <= A.CAMERA AND A.CAMERA <= 8 THEN 'PARQUEOS PUBLICOS PUERTA # 2'
                WHEN 9 <= A.CAMERA AND A.CAMERA <= 10 THEN 'LLEGADA TAXIS PUERTA # 3'
                WHEN 11 <= A.CAMERA AND A.CAMERA <= 12 THEN 'ARRIBOS PUERTA A'
                WHEN 13 <= A.CAMERA AND A.CAMERA <= 14 THEN 'ARRIBOS PUERTA B'
                WHEN 15 <= A.CAMERA AND A.CAMERA <= 16 THEN 'ARRIBOS PUERTA C'
                WHEN 17 <= A.CAMERA AND A.CAMERA <= 20 THEN 'PATIO DE COMIDAS'
                WHEN 21 <= A.CAMERA AND A.CAMERA <= 22 THEN 'ASCENSORES PB'
                WHEN 23 <= A.CAMERA AND A.CAMERA <= 24 THEN 'BAÑOS PB ZONA A - B'
                WHEN 25 <= A.CAMERA AND A.CAMERA <= 28 THEN 'ESCALERAS ELECTRICAS'
                WHEN 29 <= A.CAMERA AND A.CAMERA <= 30 THEN 'ASCENSORES 1er. PISO'
                WHEN 31 <= A.CAMERA AND A.CAMERA <= 33 THEN 'BAÑOS 1er. PISO'
                WHEN 34 <= A.CAMERA AND A.CAMERA <= 37 THEN 'TORNIQUETE 1er. PISO'
                WHEN 38 <= A.CAMERA AND A.CAMERA <= 39 THEN 'ASCENSORES 2do. PISO'
                WHEN 40 <= A.CAMERA AND A.CAMERA <= 43 THEN 'BAÑOS 2do.  PISO'
                WHEN 44 <= A.CAMERA AND A.CAMERA <= 47 THEN 'TORNIQUETES 2do. PISO'
                ELSE 'NO DEFINIDO'
            END AS GRUPO_CAMARA,
            CASE A.EVENT_TYPE
                -- WHEN 15 then 'Couting line A'
                -- WHEN 16 then 'Couting line B'
                WHEN 15 THEN 'ENTRADA'
                WHEN 16 THEN 'SALIDA'
                ELSE 'EVENT_TYPE NO DEFINIDO'
            END AS EVENT_TYPE2
        FROM
            T_ANALYTICS AS A
        WHERE 1=1
            AND A.EVENT_TYPE IN (15,16)
            -- AND CAMERA IN ('01','02')
    ) A2
WHERE 1=1
    -- AND A2.EVENT_TYPE IN (15,16)
    -- AND A2.CAMERA = '01'
    AND A2.START_DATE BETWEEN '$P!{fecha_inicio} 00:00:00' AND '$P!{fecha_fin} 23:59:59'
    -- AND A2.START_DATE BETWEEN '2015-04-01 00:00:00' AND '2015-04-30 23:59:59'
    -- AND A2.START_DATE BETWEEN '2015-01-01 00:00:00' AND '2015-07-31 23:59:59'
    -- AND A2.START_DATE BETWEEN '2015-01-01 00:00:00' AND '2015-01-31 23:59:59'
    -- << FEBRERO >>
    -- AND A2.START_DATE BETWEEN '2015-02-02 00:00:00' AND '2015-02-08 23:59:59'
    -- AND A2.START_DATE BETWEEN '2015-02-02 00:00:00' AND '2015-02-15 23:59:59'
GROUP BY
    A2.GRUPO_CAMARA,  A2.EVENT_TYPE2, A2.WEEK2, A2.DATE2, A2.CAMERA
ORDER BY
    -- A2.GRUPO_CAMARA, A2.EVENT_TYPE2, A2.CAMERA, A2.WEEK2, A2.DATE2
    A2.CAMERA, A2.EVENT_TYPE2, A2.GRUPO_CAMARA, A2.WEEK2, A2.DATE2